# Gunakan image resmi Visual Studio Code dari Microsoft
FROM mcr.microsoft.com/vscode/devcontainers/universal:1

# Atur nama pengguna dan UID sesuai kebutuhan
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Pasang ekstensi Visual Studio Code yang dibutuhkan
RUN az extension add --name azure-cli

# Aktifkan modul pengguna non-root dan atur hak akses pada folder /home/${USERNAME}
RUN mkdir -p /home/${USERNAME}/.vscode-server /home/${USERNAME}/.vscode-server-insiders /home/${USERNAME}/.vscode-remote \
    && chown -R ${USER_UID}:${USER_GID} /home/${USERNAME}

# Atur pengguna non-root
USER ${USERNAME}

# Aktifkan non-root VS Code
ENV VSCODE_UID=${USER_UID}

# Aktifkan mode non-root default
ENV VSCODE_REMOTE_CONTAINERS_DEFAULT_USERNAME=${USERNAME}

# Aktifkan mode non-root default
ENV VSCODE_REMOTE_CONTAINERS_DEFAULT_EXTENSIONS="ms-vscode-remote.remote-containers"
